abstract: an application platform for perl MVC web development
author: 'Matt S Trout, <mst@shadowcatsystems.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.61
license: gpl
name: Reaction
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.56
  DBIx::Class: 0.06002
  JSON::Syck: 0
  Module::Find: 0
  Moose: 0.05
  perl: 5.8.2
version: 0.001000_001
